### ISSUE TITLE
ERROR   -  No permission to create directory: /.config/mkdocs-document-dates/hooks

### ISSUE THREAD

**Issue by Knight-of-Code** [jaywhj/mkdocs-document-dates#17]
So I set the plugin, but getting this error `ERROR   -  No permission to create directory: /.config/mkdocs-document-dates/hooks`

I'm using docker compose and building the image with Dockerfile. The user 1000 owns the bind mount dir.

Relevant settings in compose:-
```yaml
    build:
      context: .
    image: "local/mkdocs-material:custom"    
    pull_policy: never 
    user: "1000:1000"
    security_opt:
        - no-new-privileges=true
    volumes:
      - "${DIR_PI}/mkdocs:/docs"
    stdin_open: true
    tty: true
```

Dockerfile:
```Dockerfile
FROM squidfunk/mkdocs-material

COPY requirements.txt /tmp/requirements.txt
RUN pip install -r /tmp/requirements.txt
```

requirement.txt:
```
mkdocs-document-dates

mkdocs-macros-plugin
mkdocs-glightbox
```

**Comment by Knight-of-Code** [comment]
> Can you take a screenshot of it?
> 
> The plugin's current logic for determining if it's multiple authors is to match both username and email, and if one of them is different, mark it as a different author.
> 
> You can manually specify one or more authors in the frontmatter by referring to the [Specify-Author](https://jaywhj.netlify.app/document-dates-en#Specify-Author) and [Specify-Avatar](https://jaywhj.netlify.app/document-dates-en#Specify-Avatar) sections of the documentation.
> 
> Regarding the aggregation author situation, I'll improve it in the next release

<img width="638" height="147" alt="Image" src="https://github.com/user-attachments/assets/afdc4d29-86ba-4cf0-be1a-933a9de84ba1" />

**Comment by Knight-of-Code** [comment]
> [@Knight-of-Code](https://github.com/Knight-of-Code)
> 
> I've just released a beta version `3.4.2` to TestPyPI that has fixed the 2 issues you fed back above (the second issue still requires you to configure the `.mailmap` file)
> 
> You can try installing this version with the following command:
> 
> ```
> pip install -v --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple/ mkdocs-document-dates==3.4.2
> ```
> 
> If you have no problem with it, I'll release the official version in a couple of days, then you can update it normally!

ok, i will test and comeback.

**Comment by jaywhj** [comment]
Fixed it again, see version `3.4.3` and I verified that the problems are solved, try again:

```
pip install -v --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple/ mkdocs-document-dates==3.4.3
```

The file `.mailmap` still needs to be configured, because that's the official git mechanism.

**Comment by Knight-of-Code** [comment]
> Fixed it again, see version `3.4.3` and I verified that the problems are solved, try again:
> 
> ```
> pip install -v --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple/ mkdocs-document-dates==3.4.3
> ```
> 
> The file `.mailmap` still needs to be configured, because that's the official git mechanism.

Just tested it on local and not public site
- All the pages beside Home are showing only a single author. And everywhere it's showing email i described in .mailmap, even in Home where it still shows 2 authors it's at least showing same custom email in both. 
  - so only double authors on home page.
  - some pages instead of showing my name showing my GitHub username, like home shows my name and TEST and newly added page shows GitHub name without email as below image

<img width="1260" height="471" alt="Image" src="https://github.com/user-attachments/assets/1f07cf4c-cf5d-4480-b185-5d24e1d7744c" />

Home:

<img width="1604" height="797" alt="Image" src="https://github.com/user-attachments/assets/d7638382-827b-4fae-ac19-81a0deffcf68" />

**Comment by jaywhj** [comment]
1. After configuring the `.mailmap` file it should normally show only one author, if it still shows 2 authors on the homepage, then it is possible that the .mailmap file is not configured correctly. You can verify that your .mailmap file is configured correctly by using terminal commands. Execute the following commands once when there is no .mailmap file and once when there is a .mailmap file, and then compare the output:
    ```
    git shortlog -sne
    ```

2. The author information is loaded in this order: `Front Matter` > `Git Author` > `site_author(mkdocs.yml)` > `PC Username`.
- From the screenshot, the author loaded on the Home page should be Git Author, while the TEST and Linux pages load site_author, which itself has no email (Because you didn't include these two pages in your Git management, or you never did a git commit), after you do git commit, the result is different
- If you need to customize the display of author information, you can specify it in Front Matter

**Comment by Knight-of-Code** [comment]
Ok, so just checked it on public one, and it fixed the double author issue for sure. But showing for Linux and some other pages `Knight-of-Code` as author still. Also, why do dates for everything shows today? Creation and modification both.

My site [address](https://code-chronicles.pages.dev/)
  - not ready yet so blogs are in draft mode for testing mkdocs and documentation doesn't have anything either. :)

**Comment by jaywhj** [comment]
Let me take a look at the source code of your Linux.md page and the site and repo related configuration entries in mkdocs.yml

**Comment by jaywhj** [comment]
@Knight-of-Code 

You upload the md file for the Linux page, and the mkdocs.yml file

**Comment by Knight-of-Code** [comment]
You have discord or something, so i can send you the files over it?

> [@Knight-of-Code](https://github.com/Knight-of-Code)
> 
> You upload the md file for the Linux page, and the mkdocs.yml file

**Comment by Knight-of-Code** [comment]
Linux.md solved. Dumbo me had copied a blog post file to documentation and forgot to remove author front matter. After removing, works correct. Only issue i have now is why the dates of creation is correct on local version but not on public one.

mkdocs.yml: 
```yaml
site_name: Husain's Code Chronicles
site_url: https://code-chronicles.pages.dev/
site_author: Husain Al-Jabal
site_description:  >-
  A personal code Documentation 📚 & Blog ✍️ 

repo_url: https://github.com/Knight-of-Code
repo_name: Knight-of-Code

theme:
  name: material
  language: en
  logo: assets/images/code-chronicles.png                 # logo and favicon under docs/assets
  favicon: assets/favicon.png
  icon: # find the perfect icon using icon search https://squidfunk.github.io/mkdocs-material/reference/icons-emojis/#search
    logo: material/library
    repo: simple/git
    previous: fontawesome/solid/angle-left # https://squidfunk.github.io/mkdocs-material/setup/changing-the-logo-and-icons/#site-icons
    next: fontawesome/solid/angle-right
    tag:
      html: fontawesome/brands/html5
      js: fontawesome/brands/js
      css: fontawesome/brands/css3
      lnx: fontawesome/brands/linux
      ans: material/ansible
      docr: fontawesome/brands/docker
  # font: false       # fall back to system fonts
  font: # https://fonts.google.com/
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tabs
    # - navigation.tabs.sticky # navigation tabs will lock below the header and always remain visible when scrolling down
    - navigation.tracking
    - navigation.prune
    - navigation.indexes
    - toc.follow
    # - toc.integrate # "Table of Contents" always rendered as part of the navigation sidebar on the left instead on right
    - navigation.top # "back-to-top button" it's rendered centered and just below the header
    - search.suggest
    - search.highlight
    - search.share
    - navigation.footer   # links to the previous and next page of the current page
    ### Insiders only (below)
    - navigation.instant.prefetch
    - navigation.path

  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: red
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/brightness-auto
        name: Switch to system preference

plugins:
  ### Built in Plugins (MkDocs Material)
  - search:
      lang: en
  - privacy: # some Limitations of this plugin are described here https://squidfunk.github.io/mkdocs-material/plugins/privacy/#limitations
      # cache_dir: my/custom/dir
      # links_attr_map: # Insiders only
      #   target: _blank    # add target="_blank" to all external links so they open in a new tab
  - meta      # put before blog or wont work
  - blog:
      post_url_date_format: yyyy
      post_excerpt: required      # gives error if <!-- more --> is not defined in a post. https://squidfunk.github.io/mkdocs-material/plugins/blog/#config.post_excerpt
      archive_date_format: yyyy MMMM     
      archive_url_date_format: yyyy/MM
      # blog_toc: true      # setting to leverage the table of contents to display post titles in views.
      archive_toc: true
      categories_toc: true
      draft: false        #  include posts marked as drafts when building your project: https://squidfunk.github.io/mkdocs-material/plugins/blog/?h=drafts#config.draft
      draft_on_serve: true   # include posts marked as drafts when previewing your site (mkdocs serve & docker also)
      # draft_if_future_date: true  # The plugin can automatically mark posts with future dates as drafts. When the date is past today, the post is automatically included when building your project, unless explicitly marked as draft:
      pagination_per_page: 5  # no of posts displayed per page
      # pagination_if_single_page: true     # whether or not pagination should be automatically disabled when the view only consists of a single page. enable=true
      categories_allowed:   # Validate categories against a predefined list to catch typos and block unknown categories; the blog plugin will fail the build if a category is missing.
        - Blog
        - Examples
        - Drafts
        - Festivals
      ### Insiders only
      # authors_profiles: true    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-a-blog/#adding-author-profiles
      # authors_profiles_toc: true    # The value of this setting is inherited from `blog_toc`, unless it's explicitly set.
  - tags

  ### External Plugins
  - document-dates:
      position: top            # Display position: top(after title) bottom(end of document)
      type: date               # Date type: date datetime timeago, default: date
      exclude:                 # List of excluded files
        - temp.md                  # Example: Exclude the specified file
        - blog/*                   # Example: Exclude all files in blog folder, including subfolders
      date_format: '%Y-%m-%d'  # Date format strings (e.g., %Y-%m-%d, %b %d, %Y)
      time_format: '%H:%M:%S'  # Time format strings (valid only if type=datetime)
      show_author: true        # Author display mode: true(avatar) text(text) false(hidden)
      recently-updated:   # Whether to turn on recently updated data, default: false
        limit: 10        # Limit the number of docs displayed
        exclude:         # Exclude documents you don't want to show
          - index.md
  - git-authors:      # https://timvink.github.io/mkdocs-git-authors-plugin/options.html
      # show_contribution: true
      show_line_count: true
      show_email_address: true
      # add_co_authors: true
      href: "mailto:{email}"    # "mailto:{email}" display default email from git 
      # count_empty_lines: true
      fallback_to_empty: false
      # sort_authors_by: name
      # authorship_threshold_percent: 10
      # ignore_authors:
      #     - john@doe.com
      # ignore_commits: .git-blame-ignore-revs
      exclude:
          - index.md
      # enabled: true
      # enabled_on_serve: true
      strict: true
  # - macros
  # - glightbox

nav:
  - Home: index.md
    # - About: about.md
  - Documentation:
    - wiki/Documentation.md
    - Docker:
      - wiki/Docker/overview.md
    - Linux:
      - wiki/Linux/overview.md
    - TEST: test4author.md
    - Tutorials:
      - "Pihole":
        - index.md
    - tags.md

  - Blog: # only define index.md, no need to add the individual blog posts
    - blog/index.md
    - blog/author.md

# https://squidfunk.github.io/mkdocs-material/setup/extensions/
# https://squidfunk.github.io/mkdocs-material/reference/
markdown_extensions:
  ### Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  # - tables    # it comes enabled by default
  - toc: # Table of contents https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown/#table-of-contents
      permalink: ⚓︎
      permalink_title: Anchor link to this section for reference
      toc_depth: 3

  ### Python Markdown Extensions
  # - pymdownx.arithmatex:    # useful for maths 
  #     generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.blocks.caption
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  # - pymdownx.critic:
  #     mode: view      # This option defines how the markup should be parsed, i.e. whether to just "view" all suggested changes, or alternatively "accept" or "reject" them
  - pymdownx.details    # The Details extension supercharges the Admonition extension, making the resulting call-outs collapsible, allowing them to be opened and closed by the user.
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji 
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      # options:
      #   custom_icons:
      #     - overrides/.icons
  # - pymdownx.highlight
  # - pymdownx.inlinehilite
  # - pymdownx.keys
  # - pymdownx.smartsymbols
  # - pymdownx.superfences
  # - pymdownx.tabbed:
  #     alternate_style: true
  # - pymdownx.tasklist:
  #     custom_checkbox: true

extra:
  generator: false # Remove the footer that displays "Made with Material for MkDocs"
  social:   # https://squidfunk.github.io/mkdocs-material/setup/setting-up-the-footer/#social-links
    - icon: fontawesome/brands/github
      link: https://github.com/you
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/you
    - icon: fontawesome/brands/mastodon   # automatically adds "rel=me" https://docs.joinmastodon.org/user/profile/#verification
      link: https://fosstodon.org/@you
      name: you on Fosstodon
  tags:
    HTML5: html
    JavaScript: js
    CSS: css
    Linux: lnx
    Ansible: ans
    Docker: docr
  consent:
    title: Cookie consent
    description: >-
      I use cookies to recognize your repeated visits and preferences, as well as to measure the effectiveness of my documentation and whether you find what you're searching for. With your consent, you're helping me make my documentation better. Your feedback is invaluable in refining the content so that it remains relevant and useful to those who visit this site.
    cookies:
      analytics:
        name: Google Analytics
        checked: false
### TODO setup feedback form using google forms
### Hiding the feedback widget for a document -> https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-analytics/#hiding-the-feedback-widget
  analytics:
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >-
            Thanks for your feedback! Help us improve this page by
            using our <a href="..." target="_blank" rel="noopener">feedback form</a>.

# https://squidfunk.github.io/mkdocs-material/setup/ensuring-data-privacy/#change-cookie-settings
copyright: >
  Copyright &copy; 2024 - 2025 Husain Al-Jabal –
  <a href="#__consent">Change cookie settings</a>


extra_css:
  - stylesheets/extra.css
```

**Comment by jaywhj** [comment]
See the documentation:

- Creation time: Front Matter > Cached File > Git Timestamp > File System Timestamp

First, check if the cache file `.dates_cache.jsonl` is generated and pushed to the remote repository? If none of them are present, the Git timestamp is read, and if the git commit has not been executed, the time of the file system is read

**Comment by jaywhj** [comment]
For example, suppose the file was created on 10-05, at which point you execute mkdocs build and the 10-05 timestamp is displayed

Then you commit the file to github on 10-06, at which point you run mkdocs build and it shows the 10-06 timestamp. Without special handling, the site will show the first git commit timestamp(10-06)

But this plugin has been further optimized, in your execution of git commit will automatically generate the 10-05 cache file, the cache will follow your git push action to automatically commit to github, then you run again when the site will show the date of 10-05

**Comment by Knight-of-Code** [comment]
> Looking at the logs you listed, it looks like the contents of the pre-commit file have been modified, it was originally something like the following:
> 
> #!/usr/bin/env python3
> 
> try:
>     from mkdocs_document_dates.cache_manager import update_cache
> except Exception:
>     import sys
>     # 正常退出（0 状态码），不影响 git 的后续动作
>     sys.exit(0)
> 
> if __name__ == "__main__":
>     update_cache()
> 
> Are you running in a docker container or a regular PC environment? Steps? You'll need to list a more detailed runtime environment and operational steps, along with a description of the problem, so I can help you out.
> 
> My discord id is: `aaronwqt_32904`

I didn't touch the file. I'm running in docker using compose files. 
I sent you a friend request on discord. I will message you compose and config files.

**Comment by jaywhj** [comment]
> Had to add below in compose file and run cmd `mkdocs-document-dates-hooks` from inside of container to generate files for creation dates. This solves the title error too and shows correct creation dates on my public site.
> 
> environment:
>   - HOME=/docs
> working_dir: /docs
> Closing this issue now.
> 
> Thanks, [@jaywhj](https://github.com/jaywhj). 👍

This command `mkdocs-document-dates-hooks` is reserved for installing git hooks manually in my program (as a backup), under normal circumstances, git hooks will be installed automatically when you install this plugin, so you don't need to install it again manually.

I read your steps, you need to install the plugin once in the docker environment, not in the host, and then the git hooks will be installed normally, so you won't have any problems after that!

Also, docker's environment variables need to be configured, I'll note the steps in the documentation.

Thanks for your feedback and use.
